### ISSUE TITLE
Accessing dataset

### ISSUE THREAD

**Issue by songminjae** [NathanGavenski/ABCO#1]
Hi, I'm trying to run the code.
However, the dataset link that you attached does not work at all.
 Can you please fix this?
 
 Thank you!

**Comment by NathanGavenski** [comment]
Hi, I'm so sorry it is not working anymore. 

Do you still need it? If so, I can try to find the data (our university removed the data from the link)
However, I'd suggest using our new repo [IL-Datasets](https://github.com/NathanGavenski/IL-Datasets) to create data!

**Comment by songminjae** [comment]
Thank you for your kind reply.
 I will look at the new repo instead. 
 Thank you again!
